# Generated by Django 4.0.5 on 2022-06-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
