# Generated by Django 4.0.5 on 2022-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_blog_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='intro',
            field=models.CharField(max_length=200),
        ),
    ]
